[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "table-game-chat"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = []

[tool.setuptools_scm]
